- Jenkinsfile
> fix 1.1.x to production on master

- Jenkinsfile
> fix 1.2.x jenkins identifier

- .travis.yml
- build.gradle
- src/test/groovy/app/AppSpec.groovy
> Add Travis configuration

- ocp-config/dc.yml
- src/main/groovy/app/App.groovy
> Add /health endpoint

- src/main/groovy/app/DocGen.groovy
- src/test/groovy/app/AppSpec.groovy
- src/test/groovy/app/DocGenSpec.groovy
> Replace HTML header/footer with simple text representation

- docker/Dockerfile
> Update to wkhtmltopdf 0.12.5

- src/main/groovy/app/DocGen.groovy
> Adjust header spacing

- src/main/groovy/app/DocGen.groovy
> Adjust document orientation

- Jenkinsfile
Addresses https://github.com/opendevstack/ods-core/issues/523.
> Set default branch to master instead of production

- .github/workflows/continuous-integration-workflow.yml
- .github/workflows/push-image.sh
- docker/Dockerfile
> publish the dockerimage to dockerhub

- .github/workflows/continuous-integration-workflow.yml
> add docker lables to image

- Makefile
- README.md
- build.gradle
- sonar-project.properties
Related to https://github.com/opendevstack/ods-quickstarters/issues/213.
Depends on https://github.com/opendevstack/ods-core/pull/595.
> Add code coverage

- build.gradle
- src/main/groovy/app/BitBucketDocumentTemplatesStore.groovy
- src/test/groovy/app/BitBucketDocumentTemplatesStoreSpec.groovy
- src/test/groovy/app/SpecHelper.groovy
help with better error messages on the bitbucket side.
> add better error messages for bitbucket adapter

- .github/workflows/continuous-integration-workflow.yml
- Jenkinsfile
both download urls to wkhtml changed recently ... :(
a) github action broke
b) jenkins job broke
> Bug/jenkins agent - change download url - wkhtml - moved to github

- Jenkinsfile
needed for tests - and also a good practice, given that you need to import / tag that image to use it later
> add tagging of doc gen image into jenkinsfile

- CHANGELOG.md
set date and version in changelog
> set date and version in changelog

- CHANGELOG.md
add 3.0 date to show that Unreleased is now for 4.x
> Feature/set version 4.x

- build.gradle
- src/main/groovy/app/GithubDocumentTemplatesStore.groovy
- src/test/groovy/app/GithubDocumentTemplatesStoreSpec.groovy
> add proxy support for github doc templates store - master

- .github/workflows/continuous-integration-workflow.yml
- CHANGELOG.md
- src/main/groovy/app/GithubDocumentTemplatesStore.groovy
- src/test/groovy/app/GithubDocumentTemplatesStoreSpec.groovy
> add proxy fix with protocol - for github test - master

- CHANGELOG.md
- docker/Dockerfile
- docker/entrypoint.sh
- src/main/groovy/app/App.groovy
- src/main/groovy/app/DocGen.groovy
- src/test/groovy/app/DocGenSpec.groovy
This PR fixes #64  and improve memory managment migrating from byte[] to Java Streams.
> Fix wkhtmltox hangs - 4.x

- CHANGELOG.md
- docker/Dockerfile
- docker/entrypoint.sh
- src/main/groovy/app/App.groovy
- src/main/groovy/app/DocGen.groovy
- src/test/groovy/app/DocGenSpec.groovy
This PR fixes #64  and improve memory managment migrating from byte[] to Java Streams.
> Fix wkhtmltox hangs - 3.x

- CHANGELOG.md
- build.gradle
> Removed jcenter repo from build.gradle
